# Generated by Django 3.2.16 on 2022-12-01 11:51

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221130_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='full_info',
            field=models.CharField(max_length=50, verbose_name='полное описание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='question',
            name='life_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 18, 51, 4, 749919), verbose_name='Время жизни'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 18, 51, 4, 749919), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='question',
            name='short_info',
            field=models.CharField(max_length=25, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='voted_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='проголосовавшие'),
        ),
    ]
